# Copyright 2016 The Johns Hopkins University Applied Physics Laboratory
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from ndio.service.service import Service as NdService
from abc import abstractmethod
from requests import Session

class Service(NdService):
    def __init__(self):
        super().__init__()
        self._versions = {}
        self._session = Session()
        self._session_send_opts = {}

    @property
    def session(self):
        return self._session

    @property
    def session_send_opts(self):
        return self._session_send_opts

    @session_send_opts.setter
    def session_send_opts(self, opts_dict):
        self._session_send_opts = opts_dict

    def set_auth(self, token, **kwargs):
        """Set the token for authentication/authorization.

        Attributes:
            token (string):  Token generated by the Django Rest Framework.
        """
        self._auth = token

    def get_api_impl(self, version):
        """Get service object that implements the given version.

        Attributes:
            version (string): Requested version such as '0.4'.

        Returns:
            (ndio.service.boss.Service): A service object that implements the
            requested version of the API.

        Raises:
            KeyError
        """
        return self._versions[version]

    @property
    def url_prefix(self):
        return self.base_protocol + '://' + self.base_url
